//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptv.XServer.Controls.Map.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ptv.XServer.Controls.Map.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerials.
        /// </summary>
        public static string Aerials {
            get {
                return ResourceManager.GetString("Aerials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectability.
        /// </summary>
        public static string Selectability {
            get {
                return ResourceManager.GetString("Selectability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute speed: {0} km/h.
        /// </summary>
        public static string ToolTipTrafficIncidentsAbsoluteSpeed {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsAbsoluteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay: {0} min.
        /// </summary>
        public static string ToolTipTrafficIncidentsDelay {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length: {0:0.000} km.
        /// </summary>
        public static string ToolTipTrafficIncidentsLength {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string ToolTipTrafficIncidentsMessage {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed for vehicles carrying combustibles..
        /// </summary>
        public static string ToolTipTruckAttributesCombustibles {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesCombustibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This restriction does not concern delivery vehicles..
        /// </summary>
        public static string ToolTipTruckAttributesFreeForDelivery {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesFreeForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed for vehicles carrying hazardous goods..
        /// </summary>
        public static string ToolTipTruckAttributesHazardousGoods {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesHazardousGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed for vehicles carrying goods hazardous to waters..
        /// </summary>
        public static string ToolTipTruckAttributesHazardousToWaters {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesHazardousToWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed for vehicles of load type: {0}..
        /// </summary>
        public static string ToolTipTruckAttributesLoadType {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        public static string ToolTipTruckAttributesLoadTypeGoods {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadTypeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string ToolTipTruckAttributesLoadTypeMixed {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadTypeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string ToolTipTruckAttributesLoadTypePassenger {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadTypePassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal axle load: {0:###,###} kg.
        /// </summary>
        public static string ToolTipTruckAttributesMaxAxleLoad {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxAxleLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal height: {0:0.00} m.
        /// </summary>
        public static string ToolTipTruckAttributesMaxHeight {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal length: {0:0.00} m.
        /// </summary>
        public static string ToolTipTruckAttributesMaxLength {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal weight: {0:###,###} kg.
        /// </summary>
        public static string ToolTipTruckAttributesMaxWeight {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal width: {0:0.00} m.
        /// </summary>
        public static string ToolTipTruckAttributesMaxWidth {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total permitted weight: {0:###,###} kg.
        /// </summary>
        public static string ToolTipTruckAttributesTotalPermittedWeight {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesTotalPermittedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel restriction code: {0}.
        /// </summary>
        public static string ToolTipTruckAttributesTunnelRestriction {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesTunnelRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streets.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck attributes.
        /// </summary>
        public static string TruckAttributes {
            get {
                return ResourceManager.GetString("TruckAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
